set(CHARONLOAD_CMAKE_CONFIGURE_PASSED_FILE "${CMAKE_BINARY_DIR}/charonload/cmake_configure_passed.txt")

file(REMOVE ${CHARONLOAD_CMAKE_CONFIGURE_PASSED_FILE})
file(GENERATE
    OUTPUT ${CHARONLOAD_CMAKE_CONFIGURE_PASSED_FILE}
    CONTENT "$<BOOL:TRUE>")
