name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

categories:
  - title: Added
    labels:
      - added
  - title: Changed
    labels:
      - changed
  - title: Deprecated
    labels:
      - deprecated
  - title: Removed
    labels:
      - removed
  - title: Fixed
    labels:
      - fixed

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

version-resolver:
  major:
    labels:
      - major
  minor:
    labels:
      - minor
  patch:
    labels:
      - patch
  default: patch

include-labels:
  - 'added'
  - 'changed'
  - 'deprecated'
  - 'removed'
  - 'fixed'
