name: Docs

on:
  push:
    branches:
      - main

  pull_request:
    types: [opened, reopened, synchronize]

  release:
    types:
      - published

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: '**/*requirements.txt'

      - name: Install torch CPU-only version
        run: python -m pip install -r .github/torch_cpu_requirements.txt

      - name: Install charonload
        run: python -m pip install --editable ".[dev]"

      - name: Build docs
        run: nox -s docs

      - uses: actions/upload-artifact@v4
        with:
          name: Docs HTML
          path: build/docs/html

  publish:
    name: Upload release to GitHub Pages
    runs-on: ubuntu-22.04
    if: github.event_name == 'release' && github.event.action == 'published'

    needs:
      - build

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: Docs HTML
          path: build/docs/html

      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/docs/html
          clean: true
          single-commit: true
