name: Lint

on:
  push:
    branches:
      - main

  pull_request:
    types: [opened, reopened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    strategy:
      fail-fast: false
      matrix:
        python: ["3.10", "3.11", "3.12", "3.13"]

    name: "Python ${{ matrix.python }}"
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python }}
          cache: "pip"
          cache-dependency-path: "**/*requirements.txt"

      - name: Install torch CPU-only version
        run: python -m pip install -r .github/torch_cpu_requirements.txt

      - name: Install charonload
        run: python -m pip install --editable ".[dev]"

      - name: Run linters
        run: nox -s lint

  check_lint:
    if: always()

    needs:
      - lint

    name: "Check Lint"
    runs-on: ubuntu-24.04

    steps:
      - uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
