name: Lint

on:
  push:
    branches:
      - main

  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  lint:
    strategy:
      fail-fast: false
      matrix:
        python: ['3.8', '3.9', '3.10', '3.11']

    name: "Python ${{ matrix.python }}"
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'

      - name: Install torch CPU-only version
        run: python -m pip install torch --index-url https://download.pytorch.org/whl/cpu

      - name: Install charonload
        run: python -m pip install --editable ".[dev]"

      - name: Run linters
        run: nox -s lint
