name: Release Drafter

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  Update:
    permissions:
      contents: write
      pull-requests: read

    runs-on: ubuntu-24.04

    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
